locale                   : "Beijing"
title                    : "Yaru Cao / Personal Homepage"
title_separator          : "-"

Author:
  name                     : "Yaru Cao"
  description              : "I am a PhD candidate, supervised by Professor Hongzhi Yu from Northwest Minzu University and Professor Minlie Huang from Tsinghua University."
  avatar                   : "images/myphoto.png"
  pronouns                 : ""  # 空值可以用双引号表示
  bio                      : "I am a PhD candidate, supervised by Professor Hongzhi Yu from Northwest Minzu University and Professor Minlie Huang from Tsinghua University."
  location                 : "Beijing"
  employer                 : ""  # 空值可以用双引号表示
  uri                      : ""  # 空值可以用双引号表示
  email                    : "1195825322@qq.com, y222240011@stu.xbm"
